import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import CustomFooter from "./components/CustomFooter";
import { DesignProvider } from "@/app/context/DesignContext";
import { AuthProvider } from "@/context/AuthContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar /> {/* Use the Navbar component here */}
        <DesignProvider>
        <AuthProvider>
          {children}
          </AuthProvider>
          </DesignProvider>
        <CustomFooter />
      </body>
    </html>
  );
}
